name: Build wheels

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macos-10.15]
        python-version: [3.7, 3.8, 3.9, 3.10]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Checkout submodule
        run: git submodule update --init


      - name: build
        run: python setup.py bdist_wheel

      - name: upload wheels
        uses: actions/upload-artifact@v2
        with:
          path: ./dist/*.whl
