name: Build wheels

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main, manylinux_wheels ]
  pull_request:
    branches: [ main ]

jobs:
  build_wheels_windows_x86:
    name: Build wheels on ${{ matrix.os }} x86
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.3.1
        # to supply options, put them in 'env', like:
        env:
          CIBW_ARCHS: x86

      - name: upload wheels
        uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
          
  build_wheels_windows_x64:
    name: Build wheels on ${{ matrix.python-version }} x64 ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019]
        python-version: [3.7, 3.8, 3.9, "3.10"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Install packages
        run: pip install wheel

      - name: build
        run: python setup.py bdist_wheel

      - name: upload wheels
        uses: actions/upload-artifact@v2
        with:
          path: ./dist/*.whl
          
  build_wheels_mac:
    name: Build wheels on ${{ matrix.python-version }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15]
        python-version: [3.7, 3.8, 3.9, "3.10"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install packages
        run: pip install wheel

      - name: build
        run: python setup.py bdist_wheel

      - name: upload wheels
        uses: actions/upload-artifact@v2
        with:
          path: ./dist/*.whl
          
  build_wheels_manylinux:
    name: Build manylinux wheels
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build manylinux Python wheels
        uses: RalfG/python-wheels-manylinux-build@v0.4.2-manylinux2014_x86_64

      - name: upload wheels
        uses: actions/upload-artifact@v2
        with:
          path: ./dist/*-manylinux*.whl
  
