name: Build wheels

on: [release]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macos-10.15]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Checkout submodule
        run: git submodule update --init


      - name: build
        run: python setup.py build

      - name: upload wheels
        uses: actions/upload_artifact@v2
        with:
          path: ./wheels/*.whl
